name: Simple Payment Service

on:
  push

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        pip install requirements-test.txt
        make format-check
        make lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        make install-dev
        make test
